FROM mcr.microsoft.com/devcontainers/python:1-3.13

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

COPY requirements.txt ./
RUN pip install -r requirements.txt

# Set the default shell to bash instead of sh
ENV SHELL /bin/bash